version: '3.4'

services:
  Quotation.api:
    image: ${DOCKER_REGISTRY-}Quotationapi
    build:
      context: .
      dockerfile: Serivces/Quotation/Quotation.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

  postgres:
    image: postgres:13-alpine